### ISSUE TITLE
IgnoreLine seems misleading

### ISSUE THREAD

**Issue by PeterIvanov** [gostaticanalysis/comment#8]
This method is used in several analysis tools, and it seems to work in a bizarre fashion. 
It takes the entire fileset (as I understand it, typically all files in a package) and then looks up comment by file line. 
I just had a debugging session where I found out that, unsurprisingly, this method can sometimes return comment from another file within a package. 

So it is possible that all those usages are currently broken.

**Comment by tenntenn** [comment]
Thank you for reporting.
CommentsByLine become deprecated.
